export type ProductCategory = "mens" | "womens" | "couple" | "smart" | "casual" | "premium";
export type ProductColor = {
  name: string;
  hex: string;
  imageIndex?: number;
};
export type Product = {
  id: string;
  name: string;
  slug: string;
  sku: string;
  category: ProductCategory[];
  price: number;
  originalPrice: number;
  discount: number;
  images: string[];
  colors: ProductColor[];
  movement: string;
  strap: string;
  caseMaterial: string;
  dialColor: string;
  waterResistance: string;
  caseSize: string;
  strapSize: string;
  warranty: string;
  stock: number;
  rating: number;
  reviews: number;
  description: string;
  shortDescription: string;
  features: string[];
  isFeatured?: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
};

// All product images are loaded directly from online Unsplash CDN (no local assets)
// Each image is a real watch photography from Unsplash - premium, high-quality, product-focused
const watchImages = {
  hero: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=2000&auto=format&fit=crop",
  // Men's watches - steel, chronograph, premium
  blackSteel: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=800&auto=format&fit=crop",
  blackSteel2: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=800&auto=format&fit=crop",
  blackSteel3: "https://images.unsplash.com/photo-1508685092959-9a0cea9a7daf?q=80&w=800&auto=format&fit=crop",
  chronograph: "https://images.unsplash.com/photo-1555421689-d68471e189f2?q=80&w=800&auto=format&fit=crop",
  chronograph2: "https://images.unsplash.com/photo-1555421689-3f034debb7a6?q=80&w=800&auto=format&fit=crop",
  sport: "https://images.unsplash.com/photo-1594576722512-58281a66e85e?q=80&w=800&auto=format&fit=crop",
  sport2: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=800&auto=format&fit=crop",
  premium: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=800&auto=format&fit=crop",
  premium2: "https://images.unsplash.com/photo-1548169874-53e85f753f1e?q=80&w=800&auto=format&fit=crop",
  // Women's watches
  roseGold: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=800&auto=format&fit=crop",
  roseGold2: "https://images.unsplash.com/photo-1524805444973-bf35bbb092b6?q=80&w=800&auto=format&fit=crop",
  goldElegant: "https://images.unsplash.com/photo-1508685092959-9a0cea9a7daf?q=80&w=800&auto=format&fit=crop",
  goldElegant2: "https://images.unsplash.com/photo-1548169874-53e85f753f1e?q=80&w=800&auto=format&fit=crop",
  minimalSilver: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=800&auto=format&fit=crop",
  minimalSilver2: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=800&auto=format&fit=crop",
  crystal: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=800&auto=format&fit=crop",
  crystal2: "https://images.unsplash.com/photo-1508685092959-9a0cea9a7daf?q=80&w=800&auto=format&fit=crop",
  // Casual / leather
  leatherBrown: "https://images.unsplash.com/photo-1548169874-53e85f753f1e?q=80&w=800&auto=format&fit=crop",
  heritage: "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?q=80&w=800&auto=format&fit=crop",
  heritage2: "https://images.unsplash.com/photo-1524805444973-bf35bbb092b6?q=80&w=800&auto=format&fit=crop",
  vintage: "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?q=80&w=800&auto=format&fit=crop",
  // Smart watches
  smart: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=800&auto=format&fit=crop",
  smart2: "https://images.unsplash.com/photo-1555421689-d68471e189f2?q=80&w=800&auto=format&fit=crop",
  smart3: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop",
  // Couple
  couple: "https://images.unsplash.com/photo-1548359635-e51353ca6d34?q=80&w=800&auto=format&fit=crop",
  couple2: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=800&auto=format&fit=crop",
  // Blue dial
  blueDial: "https://images.unsplash.com/photo-1518131672697-613becd4fab5?q=80&w=800&auto=format&fit=crop",
  blueDial2: "https://images.unsplash.com/photo-1524805444973-bf35bbb092b6?q=80&w=800&auto=format&fit=crop",
  // Silver mesh
  silverMesh: "https://images.unsplash.com/photo-1524805444973-bf35bbb092b6?q=80&w=800&auto=format&fit=crop",
  silverMesh2: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=800&auto=format&fit=crop",
  // Wrist shots
  wrist1: "https://images.unsplash.com/photo-1548169874-53e85f753f1e?q=80&w=800&auto=format&fit=crop",
  wrist2: "https://images.unsplash.com/photo-1508685092959-9a0cea9a7daf?q=80&w=800&auto=format&fit=crop",
  wrist3: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=800&auto=format&fit=crop",
  wrist4: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=800&auto=format&fit=crop",
  // Box / packaging
  box: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=800&auto=format&fit=crop",
  box2: "https://images.unsplash.com/photo-1548359635-e51353ca6d34?q=80&w=800&auto=format&fit=crop",
  // Additional high-quality watch images
  classicPetite: "https://images.unsplash.com/photo-1524805444973-bf35bbb092b6?q=80&w=800&auto=format&fit=crop",
  everyday: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=800&auto=format&fit=crop",
};

function img(...keys: (keyof typeof watchImages)[]): string[] {
  return keys.map(k => watchImages[k]);
}

export const products: Product[] = [
  {
    id: "tmr-001",
    name: "Executive Steel Chronograph",
    slug: "executive-steel-chronograph",
    sku: "TMR-EX-001",
    category: ["mens", "premium"],
    price: 5490,
    originalPrice: 6990,
    discount: 21,
    images: img("blackSteel", "chronograph", "blackSteel2", "wrist1", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 2 },
      { name: "Blue", hex: "#1E3A8A", imageIndex: 1 },
    ],
    movement: "Quartz Chronograph",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Black",
    waterResistance: "5 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 18,
    rating: 4.8,
    reviews: 124,
    shortDescription: "Professional chronograph with stainless steel build for everyday confidence.",
    description: "Executive Steel Chronograph is designed for modern professionals who value precision and presence. Featuring a bold 42mm stainless steel case, chronograph sub-dials, and scratch-resistant glass, this timepiece balances functionality with refined style. Perfect for office and evening occasions.",
    features: ["Chronograph Function", "Stainless Steel Case", "Date Display", "Luminous Hands"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-002",
    name: "Classic Black Dial",
    slug: "classic-black-dial",
    sku: "TMR-CB-002",
    category: ["mens"],
    price: 3490,
    originalPrice: 4490,
    discount: 22,
    images: img("blackSteel2", "heritage", "wrist3", "minimalSilver", "box2"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#D1D5DB", imageIndex: 3 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Alloy Steel",
    dialColor: "Black",
    waterResistance: "3 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 25,
    rating: 4.6,
    reviews: 89,
    shortDescription: "Timeless black dial with minimal markers for versatile everyday wear.",
    description: "Classic Black Dial brings timeless elegance to your wrist. The clean dial, slim profile and polished steel bracelet make it suitable for both formal and casual looks. A reliable quartz movement ensures accurate timekeeping.",
    features: ["Minimal Dial", "Slim Profile", "Adjustable Bracelet"],
    isFeatured: true,
  },
  {
    id: "tmr-003",
    name: "Minimal Silver Mesh",
    slug: "minimal-silver-mesh",
    sku: "TMR-MS-003",
    category: ["mens"],
    price: 4290,
    originalPrice: 5290,
    discount: 19,
    images: img("silverMesh", "minimalSilver2", "silverMesh2", "wrist3", "box"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#111111", imageIndex: 1 },
      { name: "Gold", hex: "#C9A86A", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Milanese Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver",
    waterResistance: "3 ATM",
    caseSize: "41mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 12,
    rating: 4.7,
    reviews: 67,
    shortDescription: "Ultra-thin mesh strap with minimalist dial for modern sophistication.",
    description: "Minimal Silver Mesh is crafted for those who appreciate understated luxury. The breathable Milanese mesh strap and ultra-thin case offer all-day comfort with a contemporary aesthetic.",
    features: ["Milanese Mesh", "Ultra Thin 7mm", "Minimal Markers"],
    isFeatured: true,
  },
  {
    id: "tmr-004",
    name: "Urban Sport Chronograph",
    slug: "urban-sport-chronograph",
    sku: "TMR-US-004",
    category: ["mens", "casual"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: img("chronograph2", "sport", "blackSteel", "wrist3", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Blue", hex: "#2563EB", imageIndex: 2 },
    ],
    movement: "Quartz Chronograph",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Black",
    waterResistance: "5 ATM",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 8,
    rating: 4.9,
    reviews: 142,
    shortDescription: "Bold sport chronograph built for active lifestyles and street style.",
    description: "Urban Sport Chronograph combines rugged durability with street-ready design. Large pushers, tachymeter bezel and luminous details make it both functional and striking.",
    features: ["Tachymeter", "Sport Chronograph", "Luminous Hands", "Screw-down Crown"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-005",
    name: "Heritage Leather Watch",
    slug: "heritage-leather-watch",
    sku: "TMR-HL-005",
    category: ["mens"],
    price: 4290,
    originalPrice: 5490,
    discount: 22,
    images: img("heritage", "leatherBrown", "wrist1", "heritage2", "box"),
    colors: [
      { name: "Brown", hex: "#92400E", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 3 },
    ],
    movement: "Quartz",
    strap: "Genuine Leather",
    caseMaterial: "Stainless Steel",
    dialColor: "Brown",
    waterResistance: "3 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 15,
    rating: 4.7,
    reviews: 98,
    shortDescription: "Vintage-inspired leather strap watch with warm heritage tones.",
    description: "Heritage Leather Watch draws inspiration from classic dress watches. The genuine leather strap develops a unique patina over time, while the sunray dial adds depth.",
    features: ["Genuine Leather", "Sunray Dial", "Classic Roman Numerals"],
    isFeatured: true,
  },
  {
    id: "tmr-006",
    name: "Midnight Steel",
    slug: "midnight-steel",
    sku: "TMR-MN-006",
    category: ["mens", "premium"],
    price: 8490,
    originalPrice: 10990,
    discount: 23,
    images: img("premium", "blackSteel3", "chronograph2", "wrist2", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#E5E7EB", imageIndex: 1 },
    ],
    movement: "Automatic",
    strap: "Stainless Steel",
    caseMaterial: "316L Stainless Steel",
    dialColor: "Midnight Black",
    waterResistance: "10 ATM",
    caseSize: "43mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 6,
    rating: 4.9,
    reviews: 56,
    shortDescription: "Premium automatic with midnight black dial and sapphire-coated glass.",
    description: "Midnight Steel represents TIMEORA's premium craftsmanship. With automatic movement, 316L steel and sapphire-coated glass, it's built for collectors who demand excellence.",
    features: ["Automatic Movement", "Sapphire Coated Glass", "10 ATM", "Exhibition Back"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-007",
    name: "Elegant Rose Gold",
    slug: "elegant-rose-gold",
    sku: "TMR-ER-007",
    category: ["womens", "premium"],
    price: 3490,
    originalPrice: 4490,
    discount: 22,
    images: img("roseGold", "goldElegant", "roseGold2", "wrist4", "box2"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 2 },
      { name: "Gold", hex: "#C9A86A", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Rose Gold",
    waterResistance: "3 ATM",
    caseSize: "32mm",
    strapSize: "14mm",
    warranty: "1 Year Machine Warranty",
    stock: 20,
    rating: 4.8,
    reviews: 112,
    shortDescription: "Delicate rose gold mesh watch designed for elegant everyday wear.",
    description: "Elegant Rose Gold is a celebration of feminine sophistication. The 32mm case sits gracefully on the wrist, complemented by a soft mesh strap that adjusts effortlessly.",
    features: ["32mm Petite Case", "Mesh Strap", "Crystal Markers"],
    isFeatured: true,
  },
  {
    id: "tmr-008",
    name: "Classic Petite",
    slug: "classic-petite",
    sku: "TMR-CP-008",
    category: ["womens"],
    price: 2790,
    originalPrice: 3590,
    discount: 22,
    images: img("classicPetite", "roseGold", "goldElegant2", "wrist4", "box"),
    colors: [
      { name: "Silver", hex: "#E5E7EB", imageIndex: 0 },
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 1 },
      { name: "Gold", hex: "#D4AF37", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Alloy",
    dialColor: "White",
    waterResistance: "3 ATM",
    caseSize: "30mm",
    strapSize: "14mm",
    warranty: "1 Year Machine Warranty",
    stock: 30,
    rating: 4.5,
    reviews: 76,
    shortDescription: "Petite 30mm case with clean white dial for effortless style.",
    description: "Classic Petite offers minimal elegance in a compact form. Ideal for slim wrists and everyday office wear.",
    features: ["30mm Case", "White Dial", "Adjustable Link"],
    isFeatured: true,
  },
  {
    id: "tmr-009",
    name: "Minimal Silver",
    slug: "minimal-silver-women",
    sku: "TMR-MSW-009",
    category: ["womens"],
    price: 4290,
    originalPrice: 5290,
    discount: 19,
    images: img("minimalSilver", "silverMesh", "minimalSilver2", "wrist2", "box"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver",
    waterResistance: "3 ATM",
    caseSize: "33mm",
    strapSize: "16mm",
    warranty: "1 Year Machine Warranty",
    stock: 14,
    rating: 4.6,
    reviews: 54,
    shortDescription: "Modern minimal silver watch with sunray dial.",
    description: "Minimal Silver combines Scandinavian simplicity with premium finishing. The sunray dial catches light beautifully throughout the day.",
    features: ["Sunray Dial", "Mesh Strap", "Minimal Design"],
    isFeatured: true,
  },
  {
    id: "tmr-010",
    name: "Crystal Dial",
    slug: "crystal-dial",
    sku: "TMR-CD-010",
    category: ["womens", "premium"],
    price: 5490,
    originalPrice: 6990,
    discount: 21,
    images: img("crystal", "crystal2", "goldElegant", "wrist4", "box2"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Mother of Pearl",
    waterResistance: "3 ATM",
    caseSize: "34mm",
    strapSize: "16mm",
    warranty: "1 Year Machine Warranty",
    stock: 9,
    rating: 4.9,
    reviews: 88,
    shortDescription: "Mother of pearl dial with crystal hour markers for special moments.",
    description: "Crystal Dial features genuine crystal markers and a mother-of-pearl dial that shimmers with every movement. A statement piece for celebrations.",
    features: ["Crystal Markers", "Mother of Pearl", "Premium Clasp"],
    isFeatured: true,
  },
  {
    id: "tmr-011",
    name: "Slim Gold Mesh",
    slug: "slim-gold-mesh",
    sku: "TMR-SGM-011",
    category: ["womens", "premium"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: img("goldElegant", "roseGold", "goldElegant2", "wrist2", "box"),
    colors: [
      { name: "Gold", hex: "#C9A86A", imageIndex: 0 },
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Gold Mesh",
    caseMaterial: "Stainless Steel Gold Plated",
    dialColor: "Champagne",
    waterResistance: "3 ATM",
    caseSize: "32mm",
    strapSize: "14mm",
    warranty: "1 Year Machine Warranty",
    stock: 7,
    rating: 4.8,
    reviews: 43,
    shortDescription: "Ultra-slim gold mesh with champagne dial for luxurious evenings.",
    description: "Slim Gold Mesh is TIMEORA's most luxurious women's piece, with gold-plated case and ultra-thin 6mm profile.",
    features: ["6mm Ultra Thin", "Gold Plated", "Champagne Dial"],
    isFeatured: true,
  },
  {
    id: "tmr-012",
    name: "Modern Leather Watch",
    slug: "modern-leather-watch-women",
    sku: "TMR-MLW-012",
    category: ["womens", "casual"],
    price: 3290,
    originalPrice: 4290,
    discount: 23,
    images: img("leatherBrown", "heritage", "wrist1", "silverMesh", "box2"),
    colors: [
      { name: "Brown", hex: "#92400E", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 1 },
      { name: "Beige", hex: "#D6C7B8", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Leather",
    caseMaterial: "Alloy",
    dialColor: "White",
    waterResistance: "3 ATM",
    caseSize: "36mm",
    strapSize: "18mm",
    warranty: "1 Year Machine Warranty",
    stock: 22,
    rating: 4.6,
    reviews: 61,
    shortDescription: "Soft leather strap with modern white dial for casual chic.",
    description: "Modern Leather Watch pairs soft genuine leather with a clean dial, perfect for university, office or casual outings.",
    features: ["Genuine Leather", "36mm Case", "Minimal Numerals"],
    isFeatured: false,
  },
  {
    id: "tmr-013",
    name: "Classic Couple Set",
    slug: "classic-couple-set",
    sku: "TMR-CCS-013",
    category: ["couple"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: img("couple", "blackSteel", "roseGold", "wrist1", "box2"),
    colors: [
      { name: "Black & Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver & Silver", hex: "#C0C0C0", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Black / White",
    waterResistance: "3 ATM",
    caseSize: "40mm / 32mm",
    strapSize: "20mm / 14mm",
    warranty: "1 Year Machine Warranty",
    stock: 10,
    rating: 4.9,
    reviews: 203,
    shortDescription: "Matching couple watches with complementary black and white dials.",
    description: "Classic Couple Set celebrates togetherness. Two perfectly matched timepieces with coordinated design but tailored sizes for him and her.",
    features: ["Couple Pair", "Coordinated Design", "Gift Box Included"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-014",
    name: "Minimal Couple Edition",
    slug: "minimal-couple-edition",
    sku: "TMR-MCE-014",
    category: ["couple", "casual"],
    price: 5490,
    originalPrice: 6990,
    discount: 21,
    images: img("couple2", "minimalSilver", "silverMesh", "wrist2", "box"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver / Black",
    waterResistance: "3 ATM",
    caseSize: "40mm / 32mm",
    strapSize: "20mm / 14mm",
    warranty: "1 Year Machine Warranty",
    stock: 13,
    rating: 4.7,
    reviews: 97,
    shortDescription: "Minimalist mesh couple watches for modern duos.",
    description: "Minimal Couple Edition offers understated elegance with mesh straps and clean dials, ideal for couples who prefer subtle coordination.",
    features: ["Mesh Pair", "Minimal Dial", "Lightweight"],
    isFeatured: true,
  },
  {
    id: "tmr-015",
    name: "Signature Couple",
    slug: "signature-couple",
    sku: "TMR-SC-015",
    category: ["couple", "premium"],
    price: 8490,
    originalPrice: 10990,
    discount: 23,
    images: img("premium", "couple", "goldElegant", "wrist3", "box"),
    colors: [
      { name: "Gold", hex: "#C9A86A", imageIndex: 0 },
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Gold Plated Steel",
    dialColor: "Champagne / Mother of Pearl",
    waterResistance: "3 ATM",
    caseSize: "42mm / 34mm",
    strapSize: "22mm / 16mm",
    warranty: "1 Year Machine Warranty",
    stock: 5,
    rating: 4.9,
    reviews: 64,
    shortDescription: "Premium gold-plated couple set for anniversaries and special moments.",
    description: "Signature Couple is TIMEORA's premium anniversary edition, featuring gold plating and premium gift packaging.",
    features: ["Gold Plated", "Premium Gift Box", "Anniversary Edition"],
    isFeatured: true,
  },
  {
    id: "tmr-016",
    name: "Elegant Duo",
    slug: "elegant-duo",
    sku: "TMR-ED-016",
    category: ["couple"],
    price: 9990,
    originalPrice: 12990,
    discount: 23,
    images: img("couple", "crystal", "roseGold2", "wrist1", "box2"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "White / Black",
    waterResistance: "5 ATM",
    caseSize: "40mm / 32mm",
    strapSize: "20mm / 14mm",
    warranty: "1 Year Machine Warranty",
    stock: 4,
    rating: 4.8,
    reviews: 41,
    shortDescription: "Elegant matching pair with crystal accents and premium finishing.",
    description: "Elegant Duo combines crystal hour markers with polished steel for couples who want to shine together.",
    features: ["Crystal Markers", "Polished Steel", "Couple Box"],
    isFeatured: false,
  },
  {
    id: "tmr-017",
    name: "TIMEORA Smart X1",
    slug: "timeora-smart-x1",
    sku: "TMR-SX1-017",
    category: ["smart", "casual"],
    price: 3490,
    originalPrice: 4990,
    discount: 30,
    images: img("smart", "smart2", "blackSteel", "wrist2", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 1 },
      { name: "Blue", hex: "#2563EB", imageIndex: 2 },
    ],
    movement: "Digital Smart",
    strap: "Silicone",
    caseMaterial: "Alloy + Plastic",
    dialColor: "Black Digital",
    waterResistance: "IP68",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 28,
    rating: 4.6,
    reviews: 210,
    shortDescription: "Affordable smartwatch with heart rate, steps and notification support.",
    description: "TIMEORA Smart X1 brings smart features to everyday life. Track heart rate, steps, sleep and receive call notifications directly on your wrist.",
    features: ["Heart Rate", "Step Counter", "Call Notification", "IP68"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-018",
    name: "TIMEORA Smart Active",
    slug: "timeora-smart-active",
    sku: "TMR-SA-018",
    category: ["smart"],
    price: 4290,
    originalPrice: 5990,
    discount: 28,
    images: img("smart3", "chronograph", "sport", "wrist3", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Green", hex: "#16A34A", imageIndex: 1 },
    ],
    movement: "Digital Smart",
    strap: "Silicone Sport",
    caseMaterial: "Polycarbonate",
    dialColor: "Black AMOLED",
    waterResistance: "5 ATM",
    caseSize: "45mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 16,
    rating: 4.7,
    reviews: 134,
    shortDescription: "Sport-focused smartwatch with AMOLED display and 7-day battery.",
    description: "Smart Active is built for workouts with 100+ sport modes, GPS tracking and AMOLED clarity even in sunlight.",
    features: ["AMOLED", "100+ Sport Modes", "GPS", "7-Day Battery"],
    isFeatured: true,
  },
  {
    id: "tmr-019",
    name: "TIMEORA Smart Pro",
    slug: "timeora-smart-pro",
    sku: "TMR-SP-019",
    category: ["smart", "premium"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: img("premium", "smart", "blackSteel3", "wrist1", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 1 },
    ],
    movement: "Digital Smart",
    strap: "Stainless Steel + Silicone",
    caseMaterial: "Stainless Steel",
    dialColor: "Black AMOLED",
    waterResistance: "5 ATM",
    caseSize: "46mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 9,
    rating: 4.9,
    reviews: 98,
    shortDescription: "Premium steel smartwatch with calling feature and luxury finish.",
    description: "Smart Pro combines luxury watch aesthetics with advanced smart features including Bluetooth calling, wireless charging and premium steel build.",
    features: ["Bluetooth Calling", "Steel Build", "Wireless Charging", "AMOLED"],
    isFeatured: true,
  },
  {
    id: "tmr-020",
    name: "TIMEORA Fit",
    slug: "timeora-fit",
    sku: "TMR-FIT-020",
    category: ["smart", "casual"],
    price: 2790,
    originalPrice: 3990,
    discount: 30,
    images: img("smart2", "silverMesh", "sport", "wrist2", "box2"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Pink", hex: "#EC4899", imageIndex: 1 },
      { name: "Blue", hex: "#3B82F6", imageIndex: 2 },
    ],
    movement: "Digital Smart",
    strap: "Silicone",
    caseMaterial: "Plastic",
    dialColor: "Color TFT",
    waterResistance: "IP67",
    caseSize: "38mm",
    strapSize: "18mm",
    warranty: "1 Year Machine Warranty",
    stock: 35,
    rating: 4.5,
    reviews: 187,
    shortDescription: "Lightweight fitness band style smartwatch for daily activity tracking.",
    description: "TIMEORA Fit is perfect for first-time smartwatch users. Lightweight, colorful and focused on fitness essentials.",
    features: ["Lightweight 28g", "Fitness Tracking", "Color Display", "Long Battery"],
    isFeatured: false,
  },
  {
    id: "tmr-021",
    name: "Urban Black",
    slug: "urban-black",
    sku: "TMR-UB-021",
    category: ["casual"],
    price: 2290,
    originalPrice: 2990,
    discount: 23,
    images: img("blackSteel", "blackSteel2", "sport", "wrist3", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Matte Black", hex: "#1F2937", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Silicone + Steel",
    caseMaterial: "Alloy",
    dialColor: "Black",
    waterResistance: "3 ATM",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 40,
    rating: 4.5,
    reviews: 156,
    shortDescription: "All-black urban street style watch for bold everyday presence.",
    description: "Urban Black is designed for street style enthusiasts. Full black plating, bold markers and comfortable silicone-accented strap.",
    features: ["Full Black Plating", "Bold Markers", "Street Style"],
    isFeatured: true,
  },
  {
    id: "tmr-022",
    name: "Vintage Leather",
    slug: "vintage-leather",
    sku: "TMR-VL-022",
    category: ["casual"],
    price: 3490,
    originalPrice: 4490,
    discount: 22,
    images: img("heritage", "leatherBrown", "vintage", "wrist1", "box"),
    colors: [
      { name: "Brown", hex: "#92400E", imageIndex: 0 },
      { name: "Tan", hex: "#D97706", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Vintage Leather",
    caseMaterial: "Alloy",
    dialColor: "Cream",
    waterResistance: "3 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 18,
    rating: 4.6,
    reviews: 72,
    shortDescription: "Vintage cream dial with distressed leather for retro charm.",
    description: "Vintage Leather captures retro charm with cream dial, brown distressed strap and classic sub-seconds design.",
    features: ["Vintage Design", "Cream Dial", "Distressed Leather"],
    isFeatured: true,
  },
  {
    id: "tmr-023",
    name: "Everyday Silver",
    slug: "everyday-silver",
    sku: "TMR-ES-023",
    category: ["casual", "mens"],
    price: 2790,
    originalPrice: 3490,
    discount: 20,
    images: img("silverMesh", "minimalSilver", "everyday", "wrist3", "box2"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Alloy",
    dialColor: "Silver",
    waterResistance: "3 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 27,
    rating: 4.4,
    reviews: 94,
    shortDescription: "Simple silver everyday watch that goes with everything.",
    description: "Everyday Silver is your go-to daily watch. Lightweight, versatile and easy to match with any outfit.",
    features: ["Versatile", "Lightweight", "Daily Wear"],
    isFeatured: false,
  },
  {
    id: "tmr-024",
    name: "Modern Blue Dial",
    slug: "modern-blue-dial",
    sku: "TMR-MBD-024",
    category: ["casual", "mens", "premium"],
    price: 4290,
    originalPrice: 5490,
    discount: 22,
    images: img("blueDial", "blackSteel", "blueDial2", "wrist1", "box"),
    colors: [
      { name: "Blue", hex: "#1E40AF", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 1 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Royal Blue",
    waterResistance: "5 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 11,
    rating: 4.8,
    reviews: 109,
    shortDescription: "Striking royal blue dial with polished steel for standout style.",
    description: "Modern Blue Dial makes a statement with deep royal blue sunburst dial and polished steel case. For those who want their watch to be noticed.",
    features: ["Royal Blue Sunburst", "Polished Steel", "Date Window"],
    isFeatured: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(cat: ProductCategory): Product[] {
  return products.filter(p => p.category.includes(cat));
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.isFeatured).slice(0, 12);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(p => p.id !== product.id && p.category.some(c => product.category.includes(c)))
    .slice(0, limit);
}

export const categories = [
  { id: "mens", label: "Men's Watches", slug: "mens", image: watchImages.blackSteel, count: products.filter(p => p.category.includes("mens")).length },
  { id: "womens", label: "Women's Watches", slug: "womens", image: watchImages.roseGold, count: products.filter(p => p.category.includes("womens")).length },
  { id: "couple", label: "Couple Watches", slug: "couple", image: watchImages.couple, count: products.filter(p => p.category.includes("couple")).length },
  { id: "smart", label: "Smart Watches", slug: "smart", image: watchImages.smart, count: products.filter(p => p.category.includes("smart")).length },
  { id: "casual", label: "Casual Watches", slug: "casual", image: watchImages.leatherBrown, count: products.filter(p => p.category.includes("casual")).length },
  { id: "premium", label: "Premium Collection", slug: "premium", image: watchImages.premium, count: products.filter(p => p.category.includes("premium")).length },
] as const;

export const heroImage = watchImages.hero;
