export type ProductCategory = "mens" | "womens" | "couple" | "smart" | "casual" | "premium";
export type ProductColor = {
  name: string;
  hex: string;
  imageIndex?: number;
};
export type Product = {
  id: string;
  name: string;
  slug: string;
  sku: string;
  category: ProductCategory[];
  price: number;
  originalPrice: number;
  discount: number;
  images: string[];
  colors: ProductColor[];
  movement: string;
  strap: string;
  caseMaterial: string;
  dialColor: string;
  waterResistance: string;
  caseSize: string;
  strapSize: string;
  warranty: string;
  stock: number;
  rating: number;
  reviews: number;
  description: string;
  shortDescription: string;
  features: string[];
  isFeatured?: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
};

/** Local studio product photography — always available offline */
const I = {
  hero: "/watches/hero.jpg",
  chrono: "/watches/chrono-black.jpg",
  classic: "/watches/classic-black.jpg",
  mesh: "/watches/silver-mesh.jpg",
  sport: "/watches/sport-chrono.jpg",
  leather: "/watches/leather-heritage.jpg",
  midnight: "/watches/midnight-steel.jpg",
  rose: "/watches/rose-gold.jpg",
  petite: "/watches/petite-silver.jpg",
  crystal: "/watches/crystal-pearl.jpg",
  couple: "/watches/couple-set.jpg",
  couple2: "/watches/couple-silver.jpg",
  blue: "/watches/blue-dial.jpg",
  urban: "/watches/urban-black.jpg",
  vintage: "/watches/vintage.jpg",
  wrist: "/watches/wrist-shot.jpg",
  smart: "/watches/smart-black.jpg",
  gold: "/watches/gold-mesh.jpg",
  leatherW: "/watches/women-leather.jpg",
  diver: "/watches/navy-diver.jpg",
  box: "/watches/box.jpg",
} as const;

function g(...keys: (keyof typeof I)[]): string[] {
  return keys.map(k => I[k]);
}

export const products: Product[] = [
  {
    id: "tmr-001",
    name: "Executive Steel Chronograph",
    slug: "executive-steel-chronograph",
    sku: "TMR-EX-001",
    category: ["mens", "premium"],
    price: 5490,
    originalPrice: 6990,
    discount: 21,
    images: g("chrono", "sport", "classic", "wrist", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 2 },
      { name: "Blue", hex: "#1E3A8A", imageIndex: 1 },
    ],
    movement: "Quartz Chronograph",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Black",
    waterResistance: "5 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 18,
    rating: 4.8,
    reviews: 124,
    shortDescription: "Professional chronograph with stainless steel build for everyday confidence.",
    description: "Executive Steel Chronograph is designed for modern professionals who value precision and presence. Featuring a bold 42mm stainless steel case, chronograph sub-dials, and scratch-resistant glass, this timepiece balances functionality with refined style. Perfect for office and evening occasions.",
    features: ["Chronograph Function", "Stainless Steel Case", "Date Display", "Luminous Hands"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-002",
    name: "Classic Black Dial",
    slug: "classic-black-dial",
    sku: "TMR-CB-002",
    category: ["mens"],
    price: 3490,
    originalPrice: 4490,
    discount: 22,
    images: g("classic", "chrono", "mesh", "wrist", "blue"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#D1D5DB", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Alloy Steel",
    dialColor: "Black",
    waterResistance: "3 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 25,
    rating: 4.6,
    reviews: 89,
    shortDescription: "Timeless black dial with minimal markers for versatile everyday wear.",
    description: "Classic Black Dial brings timeless elegance to your wrist. The clean dial, slim profile and polished steel bracelet make it suitable for both formal and casual looks. A reliable quartz movement ensures accurate timekeeping.",
    features: ["Minimal Dial", "Slim Profile", "Adjustable Bracelet"],
    isFeatured: true,
  },
  {
    id: "tmr-003",
    name: "Minimal Silver Mesh",
    slug: "minimal-silver-mesh",
    sku: "TMR-MS-003",
    category: ["mens"],
    price: 4290,
    originalPrice: 5290,
    discount: 19,
    images: g("mesh", "petite", "classic", "wrist", "crystal"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#111111", imageIndex: 2 },
      { name: "Gold", hex: "#C9A86A", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Milanese Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver",
    waterResistance: "3 ATM",
    caseSize: "41mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 12,
    rating: 4.7,
    reviews: 67,
    shortDescription: "Ultra-thin mesh strap with minimalist dial for modern sophistication.",
    description: "Minimal Silver Mesh is crafted for those who appreciate understated luxury. The breathable Milanese mesh strap and ultra-thin case offer all-day comfort with a contemporary aesthetic.",
    features: ["Milanese Mesh", "Ultra Thin 7mm", "Minimal Markers"],
    isFeatured: true,
  },
  {
    id: "tmr-004",
    name: "Urban Sport Chronograph",
    slug: "urban-sport-chronograph",
    sku: "TMR-US-004",
    category: ["mens", "casual"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: g("sport", "urban", "chrono", "wrist", "classic"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Blue", hex: "#2563EB", imageIndex: 2 },
    ],
    movement: "Quartz Chronograph",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Black",
    waterResistance: "5 ATM",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 8,
    rating: 4.9,
    reviews: 142,
    shortDescription: "Bold sport chronograph built for active lifestyles and street style.",
    description: "Urban Sport Chronograph combines rugged durability with street-ready design. Large pushers, tachymeter bezel and luminous details make it both functional and striking.",
    features: ["Tachymeter", "Sport Chronograph", "Luminous Hands", "Screw-down Crown"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-005",
    name: "Heritage Leather Watch",
    slug: "heritage-leather-watch",
    sku: "TMR-HL-005",
    category: ["mens"],
    price: 4290,
    originalPrice: 5490,
    discount: 22,
    images: g("leather", "vintage", "midnight", "wrist", "classic"),
    colors: [
      { name: "Brown", hex: "#92400E", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Genuine Leather",
    caseMaterial: "Stainless Steel",
    dialColor: "Brown",
    waterResistance: "3 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 15,
    rating: 4.7,
    reviews: 98,
    shortDescription: "Vintage-inspired leather strap watch with warm heritage tones.",
    description: "Heritage Leather Watch draws inspiration from classic dress watches. The genuine leather strap develops a unique patina over time, while the sunray dial adds depth.",
    features: ["Genuine Leather", "Sunray Dial", "Classic Roman Numerals"],
    isFeatured: true,
  },
  {
    id: "tmr-006",
    name: "Midnight Steel",
    slug: "midnight-steel",
    sku: "TMR-MN-006",
    category: ["mens", "premium"],
    price: 8490,
    originalPrice: 10990,
    discount: 23,
    images: g("midnight", "chrono", "urban", "wrist", "sport"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#E5E7EB", imageIndex: 1 },
    ],
    movement: "Automatic",
    strap: "Stainless Steel",
    caseMaterial: "316L Stainless Steel",
    dialColor: "Midnight Black",
    waterResistance: "10 ATM",
    caseSize: "43mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 6,
    rating: 4.9,
    reviews: 56,
    shortDescription: "Premium automatic with midnight black dial and sapphire-coated glass.",
    description: "Midnight Steel represents TIMEORA's premium craftsmanship. With automatic movement, 316L steel and sapphire-coated glass, it's built for collectors who demand excellence.",
    features: ["Automatic Movement", "Sapphire Coated Glass", "10 ATM", "Exhibition Back"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-007",
    name: "Elegant Rose Gold",
    slug: "elegant-rose-gold",
    sku: "TMR-ER-007",
    category: ["womens", "premium"],
    price: 3490,
    originalPrice: 4490,
    discount: 22,
    images: g("rose", "crystal", "petite", "wrist", "mesh"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 2 },
      { name: "Gold", hex: "#C9A86A", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Rose Gold",
    waterResistance: "3 ATM",
    caseSize: "32mm",
    strapSize: "14mm",
    warranty: "1 Year Machine Warranty",
    stock: 20,
    rating: 4.8,
    reviews: 112,
    shortDescription: "Delicate rose gold mesh watch designed for elegant everyday wear.",
    description: "Elegant Rose Gold is a celebration of feminine sophistication. The 32mm case sits gracefully on the wrist, complemented by a soft mesh strap that adjusts effortlessly.",
    features: ["32mm Petite Case", "Mesh Strap", "Crystal Markers"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-008",
    name: "Classic Petite",
    slug: "classic-petite",
    sku: "TMR-CP-008",
    category: ["womens"],
    price: 2790,
    originalPrice: 3590,
    discount: 22,
    images: g("petite", "mesh", "crystal", "wrist", "rose"),
    colors: [
      { name: "Silver", hex: "#E5E7EB", imageIndex: 0 },
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 4 },
      { name: "Gold", hex: "#D4AF37", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Alloy",
    dialColor: "White",
    waterResistance: "3 ATM",
    caseSize: "30mm",
    strapSize: "14mm",
    warranty: "1 Year Machine Warranty",
    stock: 30,
    rating: 4.5,
    reviews: 76,
    shortDescription: "Petite 30mm case with clean white dial for effortless style.",
    description: "Classic Petite offers minimal elegance in a compact form. Ideal for slim wrists and everyday office wear.",
    features: ["30mm Case", "White Dial", "Adjustable Link"],
    isFeatured: true,
  },
  {
    id: "tmr-009",
    name: "Minimal Silver",
    slug: "minimal-silver-women",
    sku: "TMR-MSW-009",
    category: ["womens"],
    price: 4290,
    originalPrice: 5290,
    discount: 19,
    images: g("mesh", "petite", "crystal", "wrist", "classic"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 4 },
    ],
    movement: "Quartz",
    strap: "Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver",
    waterResistance: "3 ATM",
    caseSize: "33mm",
    strapSize: "16mm",
    warranty: "1 Year Machine Warranty",
    stock: 14,
    rating: 4.6,
    reviews: 54,
    shortDescription: "Modern minimal silver watch with sunray dial.",
    description: "Minimal Silver combines Scandinavian simplicity with premium finishing. The sunray dial catches light beautifully throughout the day.",
    features: ["Sunray Dial", "Mesh Strap", "Minimal Design"],
    isFeatured: true,
  },
  {
    id: "tmr-010",
    name: "Crystal Dial",
    slug: "crystal-dial",
    sku: "TMR-CD-010",
    category: ["womens", "premium"],
    price: 5490,
    originalPrice: 6990,
    discount: 21,
    images: g("crystal", "rose", "petite", "wrist", "mesh"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Mother of Pearl",
    waterResistance: "3 ATM",
    caseSize: "34mm",
    strapSize: "16mm",
    warranty: "1 Year Machine Warranty",
    stock: 9,
    rating: 4.9,
    reviews: 88,
    shortDescription: "Mother of pearl dial with crystal hour markers for special moments.",
    description: "Crystal Dial features genuine crystal markers and a mother-of-pearl dial that shimmers with every movement. A statement piece for celebrations.",
    features: ["Crystal Markers", "Mother of Pearl", "Premium Clasp"],
    isFeatured: true,
  },
  {
    id: "tmr-011",
    name: "Slim Gold Mesh",
    slug: "slim-gold-mesh",
    sku: "TMR-SGM-011",
    category: ["womens", "premium"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: g("gold", "rose", "crystal", "wrist", "box"),
    colors: [
      { name: "Gold", hex: "#C9A86A", imageIndex: 0 },
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
    ],
    movement: "Quartz",
    strap: "Gold Mesh",
    caseMaterial: "Stainless Steel Gold Plated",
    dialColor: "Champagne",
    waterResistance: "3 ATM",
    caseSize: "32mm",
    strapSize: "14mm",
    warranty: "1 Year Machine Warranty",
    stock: 7,
    rating: 4.8,
    reviews: 43,
    shortDescription: "Ultra-slim gold mesh with champagne dial for luxurious evenings.",
    description: "Slim Gold Mesh is TIMEORA's most luxurious women's piece, with gold-plated case and ultra-thin 6mm profile.",
    features: ["6mm Ultra Thin", "Gold Plated", "Champagne Dial"],
    isFeatured: true,
  },
  {
    id: "tmr-012",
    name: "Modern Leather Watch",
    slug: "modern-leather-watch-women",
    sku: "TMR-MLW-012",
    category: ["womens", "casual"],
    price: 3290,
    originalPrice: 4290,
    discount: 23,
    images: g("leatherW", "leather", "petite", "wrist", "vintage"),
    colors: [
      { name: "Brown", hex: "#92400E", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 1 },
      { name: "Beige", hex: "#D6C7B8", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Leather",
    caseMaterial: "Alloy",
    dialColor: "White",
    waterResistance: "3 ATM",
    caseSize: "36mm",
    strapSize: "18mm",
    warranty: "1 Year Machine Warranty",
    stock: 22,
    rating: 4.6,
    reviews: 61,
    shortDescription: "Soft leather strap with modern white dial for casual chic.",
    description: "Modern Leather Watch pairs soft genuine leather with a clean dial, perfect for university, office or casual outings.",
    features: ["Genuine Leather", "36mm Case", "Minimal Numerals"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-013",
    name: "Classic Couple Set",
    slug: "classic-couple-set",
    sku: "TMR-CCS-013",
    category: ["couple"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: g("couple", "chrono", "rose", "wrist", "couple2"),
    colors: [
      { name: "Black & Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver & Silver", hex: "#C0C0C0", imageIndex: 4 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Black / White",
    waterResistance: "3 ATM",
    caseSize: "40mm / 32mm",
    strapSize: "20mm / 14mm",
    warranty: "1 Year Machine Warranty",
    stock: 10,
    rating: 4.9,
    reviews: 203,
    shortDescription: "Matching couple watches with complementary black and white dials.",
    description: "Classic Couple Set celebrates togetherness. Two perfectly matched timepieces with coordinated design but tailored sizes for him and her.",
    features: ["Couple Pair", "Coordinated Design", "Gift Box Included"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-014",
    name: "Minimal Couple Edition",
    slug: "minimal-couple-edition",
    sku: "TMR-MCE-014",
    category: ["couple", "casual"],
    price: 5490,
    originalPrice: 6990,
    discount: 21,
    images: g("couple2", "mesh", "petite", "wrist", "couple"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 4 },
    ],
    movement: "Quartz",
    strap: "Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver / Black",
    waterResistance: "3 ATM",
    caseSize: "40mm / 32mm",
    strapSize: "20mm / 14mm",
    warranty: "1 Year Machine Warranty",
    stock: 13,
    rating: 4.7,
    reviews: 97,
    shortDescription: "Minimalist mesh couple watches for modern duos.",
    description: "Minimal Couple Edition offers understated elegance with mesh straps and clean dials, ideal for couples who prefer subtle coordination.",
    features: ["Mesh Pair", "Minimal Dial", "Lightweight"],
    isFeatured: true,
  },
  {
    id: "tmr-015",
    name: "Signature Couple",
    slug: "signature-couple",
    sku: "TMR-SC-015",
    category: ["couple", "premium"],
    price: 8490,
    originalPrice: 10990,
    discount: 23,
    images: g("couple", "midnight", "rose", "wrist", "crystal"),
    colors: [
      { name: "Gold", hex: "#C9A86A", imageIndex: 0 },
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Gold Plated Steel",
    dialColor: "Champagne / Mother of Pearl",
    waterResistance: "3 ATM",
    caseSize: "42mm / 34mm",
    strapSize: "22mm / 16mm",
    warranty: "1 Year Machine Warranty",
    stock: 5,
    rating: 4.9,
    reviews: 64,
    shortDescription: "Premium gold-plated couple set for anniversaries and special moments.",
    description: "Signature Couple is TIMEORA's premium anniversary edition, featuring gold plating and premium gift packaging.",
    features: ["Gold Plated", "Premium Gift Box", "Anniversary Edition"],
    isFeatured: true,
  },
  {
    id: "tmr-016",
    name: "Elegant Duo",
    slug: "elegant-duo",
    sku: "TMR-ED-016",
    category: ["couple"],
    price: 9990,
    originalPrice: 12990,
    discount: 23,
    images: g("couple", "crystal", "rose", "wrist", "couple2"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 4 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "White / Black",
    waterResistance: "5 ATM",
    caseSize: "40mm / 32mm",
    strapSize: "20mm / 14mm",
    warranty: "1 Year Machine Warranty",
    stock: 4,
    rating: 4.8,
    reviews: 41,
    shortDescription: "Elegant matching pair with crystal accents and premium finishing.",
    description: "Elegant Duo combines crystal hour markers with polished steel for couples who want to shine together.",
    features: ["Crystal Markers", "Polished Steel", "Couple Box"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-017",
    name: "TIMEORA Smart X1",
    slug: "timeora-smart-x1",
    sku: "TMR-SX1-017",
    category: ["smart", "casual"],
    price: 3490,
    originalPrice: 4990,
    discount: 30,
    images: g("smart", "urban", "sport", "wrist", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 1 },
      { name: "Blue", hex: "#2563EB", imageIndex: 2 },
    ],
    movement: "Digital Smart",
    strap: "Silicone",
    caseMaterial: "Alloy + Plastic",
    dialColor: "Black Digital",
    waterResistance: "IP68",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 28,
    rating: 4.6,
    reviews: 210,
    shortDescription: "Affordable smartwatch with heart rate, steps and notification support.",
    description: "TIMEORA Smart X1 brings smart features to everyday life. Track heart rate, steps, sleep and receive call notifications directly on your wrist.",
    features: ["Heart Rate", "Step Counter", "Call Notification", "IP68"],
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: "tmr-018",
    name: "TIMEORA Smart Active",
    slug: "timeora-smart-active",
    sku: "TMR-SA-018",
    category: ["smart"],
    price: 4290,
    originalPrice: 5990,
    discount: 28,
    images: g("smart", "sport", "urban", "wrist", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Green", hex: "#16A34A", imageIndex: 1 },
    ],
    movement: "Digital Smart",
    strap: "Silicone Sport",
    caseMaterial: "Polycarbonate",
    dialColor: "Black AMOLED",
    waterResistance: "5 ATM",
    caseSize: "45mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 16,
    rating: 4.7,
    reviews: 134,
    shortDescription: "Sport-focused smartwatch with AMOLED display and 7-day battery.",
    description: "Smart Active is built for workouts with 100+ sport modes, GPS tracking and AMOLED clarity even in sunlight.",
    features: ["AMOLED", "100+ Sport Modes", "GPS", "7-Day Battery"],
    isFeatured: true,
  },
  {
    id: "tmr-019",
    name: "TIMEORA Smart Pro",
    slug: "timeora-smart-pro",
    sku: "TMR-SP-019",
    category: ["smart", "premium"],
    price: 6990,
    originalPrice: 8990,
    discount: 22,
    images: g("smart", "midnight", "urban", "wrist", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 1 },
    ],
    movement: "Digital Smart",
    strap: "Stainless Steel + Silicone",
    caseMaterial: "Stainless Steel",
    dialColor: "Black AMOLED",
    waterResistance: "5 ATM",
    caseSize: "46mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 9,
    rating: 4.9,
    reviews: 98,
    shortDescription: "Premium steel smartwatch with calling feature and luxury finish.",
    description: "Smart Pro combines luxury watch aesthetics with advanced smart features including Bluetooth calling, wireless charging and premium steel build.",
    features: ["Bluetooth Calling", "Steel Build", "Wireless Charging", "AMOLED"],
    isFeatured: true,
  },
  {
    id: "tmr-020",
    name: "TIMEORA Fit",
    slug: "timeora-fit",
    sku: "TMR-FIT-020",
    category: ["smart", "casual"],
    price: 2790,
    originalPrice: 3990,
    discount: 30,
    images: g("smart", "urban", "sport", "wrist", "mesh"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Pink", hex: "#EC4899", imageIndex: 1 },
      { name: "Blue", hex: "#3B82F6", imageIndex: 2 },
    ],
    movement: "Digital Smart",
    strap: "Silicone",
    caseMaterial: "Plastic",
    dialColor: "Color TFT",
    waterResistance: "IP67",
    caseSize: "38mm",
    strapSize: "18mm",
    warranty: "1 Year Machine Warranty",
    stock: 35,
    rating: 4.5,
    reviews: 187,
    shortDescription: "Lightweight fitness band style smartwatch for daily activity tracking.",
    description: "TIMEORA Fit is perfect for first-time smartwatch users. Lightweight, colorful and focused on fitness essentials.",
    features: ["Lightweight 28g", "Fitness Tracking", "Color Display", "Long Battery"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-021",
    name: "Urban Black",
    slug: "urban-black",
    sku: "TMR-UB-021",
    category: ["casual"],
    price: 2290,
    originalPrice: 2990,
    discount: 23,
    images: g("urban", "sport", "chrono", "wrist", "classic"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Matte Black", hex: "#1F2937", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Silicone + Steel",
    caseMaterial: "Alloy",
    dialColor: "Black",
    waterResistance: "3 ATM",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 40,
    rating: 4.5,
    reviews: 156,
    shortDescription: "All-black urban street style watch for bold everyday presence.",
    description: "Urban Black is designed for street style enthusiasts. Full black plating, bold markers and comfortable silicone-accented strap.",
    features: ["Full Black Plating", "Bold Markers", "Street Style"],
    isFeatured: true,
  },
  {
    id: "tmr-022",
    name: "Vintage Leather",
    slug: "vintage-leather",
    sku: "TMR-VL-022",
    category: ["casual"],
    price: 3490,
    originalPrice: 4490,
    discount: 22,
    images: g("vintage", "leather", "midnight", "wrist", "classic"),
    colors: [
      { name: "Brown", hex: "#92400E", imageIndex: 0 },
      { name: "Tan", hex: "#D97706", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Vintage Leather",
    caseMaterial: "Alloy",
    dialColor: "Cream",
    waterResistance: "3 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 18,
    rating: 4.6,
    reviews: 72,
    shortDescription: "Vintage cream dial with distressed leather for retro charm.",
    description: "Vintage Leather captures retro charm with cream dial, brown distressed strap and classic sub-seconds design.",
    features: ["Vintage Design", "Cream Dial", "Distressed Leather"],
    isFeatured: true,
  },
  {
    id: "tmr-023",
    name: "Everyday Silver",
    slug: "everyday-silver",
    sku: "TMR-ES-023",
    category: ["casual", "mens"],
    price: 2790,
    originalPrice: 3490,
    discount: 20,
    images: g("mesh", "petite", "classic", "wrist", "blue"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Alloy",
    dialColor: "Silver",
    waterResistance: "3 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 27,
    rating: 4.4,
    reviews: 94,
    shortDescription: "Simple silver everyday watch that goes with everything.",
    description: "Everyday Silver is your go-to daily watch. Lightweight, versatile and easy to match with any outfit.",
    features: ["Versatile", "Lightweight", "Daily Wear"],
    isFeatured: true,
  },
  {
    id: "tmr-024",
    name: "Modern Blue Dial",
    slug: "modern-blue-dial",
    sku: "TMR-MBD-024",
    category: ["casual", "mens", "premium"],
    price: 4290,
    originalPrice: 5490,
    discount: 22,
    images: g("diver", "blue", "classic", "wrist", "box"),
    colors: [
      { name: "Blue", hex: "#1E40AF", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 1 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 2 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Royal Blue",
    waterResistance: "5 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 11,
    rating: 4.8,
    reviews: 109,
    shortDescription: "Striking royal blue dial with polished steel for standout style.",
    description: "Modern Blue Dial makes a statement with deep royal blue sunburst dial and polished steel case. For those who want their watch to be noticed.",
    features: ["Royal Blue Sunburst", "Polished Steel", "Date Window"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-025",
    name: "Royal Navy Classic",
    slug: "royal-navy-classic",
    sku: "TMR-RN-025",
    category: ["mens", "premium"],
    price: 5890,
    originalPrice: 7490,
    discount: 21,
    images: g("diver", "blue", "chrono", "wrist", "box"),
    colors: [
      { name: "Navy", hex: "#1E3A8A", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Navy",
    waterResistance: "5 ATM",
    caseSize: "41mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 14,
    rating: 4.7,
    reviews: 58,
    shortDescription: "Deep navy dial with polished steel — boardroom ready.",
    description: "Royal Navy Classic is a refined everyday dress watch. The navy sunburst dial sits in a 41mm steel case with a matching bracelet that dresses up or down.",
    features: ["Navy Sunburst Dial", "Date Window", "Polished Bezel"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-026",
    name: "Blush Crystal Mini",
    slug: "blush-crystal-mini",
    sku: "TMR-BCM-026",
    category: ["womens"],
    price: 3190,
    originalPrice: 4190,
    discount: 24,
    images: g("crystal", "rose", "petite", "wrist", "mesh"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Blush", hex: "#E8B4B8", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Blush Pearl",
    waterResistance: "3 ATM",
    caseSize: "28mm",
    strapSize: "12mm",
    warranty: "1 Year Machine Warranty",
    stock: 19,
    rating: 4.6,
    reviews: 47,
    shortDescription: "Tiny 28mm blush pearl dial with crystal sparkle.",
    description: "Blush Crystal Mini is made for slender wrists. A shimmering pearl dial and crystal indices make it a daily jewellery piece.",
    features: ["28mm Mini Case", "Crystal Indices", "Pearl Dial"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-027",
    name: "Dual Tone Couple",
    slug: "dual-tone-couple",
    sku: "TMR-DTC-027",
    category: ["couple"],
    price: 7490,
    originalPrice: 9490,
    discount: 21,
    images: g("couple2", "couple", "mesh", "wrist", "petite"),
    colors: [
      { name: "Silver Dual", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Two Tone", hex: "#C9A86A", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Silver / Ivory",
    waterResistance: "3 ATM",
    caseSize: "40mm / 32mm",
    strapSize: "20mm / 14mm",
    warranty: "1 Year Machine Warranty",
    stock: 11,
    rating: 4.8,
    reviews: 73,
    shortDescription: "Two-tone couple set that photographs beautifully together.",
    description: "Dual Tone Couple is designed as a gift-ready pair with complementary sizes, shared finishing and a presentation box.",
    features: ["Two-Tone Finish", "Gift Box", "Matching Hands"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-028",
    name: "TIMEORA Smart Pulse",
    slug: "timeora-smart-pulse",
    sku: "TMR-SPU-028",
    category: ["smart"],
    price: 3990,
    originalPrice: 5290,
    discount: 25,
    images: g("smart", "sport", "urban", "wrist", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Navy", hex: "#1E3A8A", imageIndex: 1 },
    ],
    movement: "Digital Smart",
    strap: "Silicone",
    caseMaterial: "Alloy",
    dialColor: "AMOLED",
    waterResistance: "IP68",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 21,
    rating: 4.6,
    reviews: 81,
    shortDescription: "SpO2, heart-rate and sleep tracking in a slim smart case.",
    description: "Smart Pulse focuses on health metrics with round-the-clock heart rate, SpO2 and a bright always-on display.",
    features: ["SpO2", "24h Heart Rate", "Sleep Score", "Always-On"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-029",
    name: "Field Khaki Leather",
    slug: "field-khaki-leather",
    sku: "TMR-FK-029",
    category: ["casual", "mens"],
    price: 3890,
    originalPrice: 4890,
    discount: 20,
    images: g("leather", "vintage", "classic", "wrist", "midnight"),
    colors: [
      { name: "Khaki", hex: "#78716C", imageIndex: 0 },
      { name: "Brown", hex: "#92400E", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Leather",
    caseMaterial: "Stainless Steel",
    dialColor: "Khaki",
    waterResistance: "5 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 16,
    rating: 4.5,
    reviews: 39,
    shortDescription: "Field-inspired khaki dial with rugged leather strap.",
    description: "Field Khaki Leather is a weekend watch — warm dial, stitched leather and a tool-watch attitude without the bulk.",
    features: ["Field Numerals", "Stitched Leather", "Luminous Hands"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-030",
    name: "Limited Automatic Gold",
    slug: "limited-automatic-gold",
    sku: "TMR-LAG-030",
    category: ["premium", "mens"],
    price: 9990,
    originalPrice: 12990,
    discount: 23,
    images: g("gold", "midnight", "leather", "wrist", "box"),
    colors: [
      { name: "Gold", hex: "#C9A24A", imageIndex: 0 },
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
    ],
    movement: "Automatic",
    strap: "Genuine Leather",
    caseMaterial: "316L Gold Tone Steel",
    dialColor: "Black",
    waterResistance: "5 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 3,
    rating: 5,
    reviews: 22,
    shortDescription: "Limited automatic with gold-tone case and exhibition movement.",
    description: "Limited Automatic Gold is TIMEORA's collector piece — automatic movement, gold-tone finishing and a numbered limited run.",
    features: ["Limited Edition", "Automatic", "Exhibition Back", "Gold Tone"],
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
  },
  {
    id: "tmr-031",
    name: "Diver Sport 200",
    slug: "diver-sport-200",
    sku: "TMR-DS-031",
    category: ["mens", "casual"],
    price: 6490,
    originalPrice: 8290,
    discount: 22,
    images: g("diver", "sport", "blue", "wrist", "box"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Blue", hex: "#1D4ED8", imageIndex: 4 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Black",
    waterResistance: "20 ATM",
    caseSize: "44mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 9,
    rating: 4.8,
    reviews: 66,
    shortDescription: "200m water-resistant diver with rotating bezel.",
    description: "Diver Sport 200 is built for weekends by the water. Unidirectional bezel, 20 ATM rating and a solid steel bracelet.",
    features: ["20 ATM", "Rotating Bezel", "Screw Crown", "Lume"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-032",
    name: "Ivory Pearl Link",
    slug: "ivory-pearl-link",
    sku: "TMR-IPL-032",
    category: ["womens", "premium"],
    price: 4790,
    originalPrice: 5990,
    discount: 20,
    images: g("petite", "crystal", "rose", "wrist", "mesh"),
    colors: [
      { name: "Ivory", hex: "#F7F1E6", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
    ],
    movement: "Quartz",
    strap: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    dialColor: "Ivory",
    waterResistance: "3 ATM",
    caseSize: "31mm",
    strapSize: "14mm",
    warranty: "1 Year Machine Warranty",
    stock: 17,
    rating: 4.7,
    reviews: 51,
    shortDescription: "Ivory dial on a five-link bracelet — quiet luxury.",
    description: "Ivory Pearl Link is a refined office-to-evening watch with a creamy dial and polished five-link bracelet.",
    features: ["Ivory Dial", "Five-Link Bracelet", "Slim 7mm"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-033",
    name: "Night Tourbillon Style",
    slug: "night-tourbillon-style",
    sku: "TMR-NT-033",
    category: ["premium"],
    price: 8990,
    originalPrice: 11990,
    discount: 25,
    images: g("midnight", "smart", "urban", "wrist", "hero"),
    colors: [
      { name: "Black", hex: "#0A0A0A", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 1 },
    ],
    movement: "Automatic",
    strap: "Alligator-grain Leather",
    caseMaterial: "316L Stainless Steel",
    dialColor: "Obsidian",
    waterResistance: "5 ATM",
    caseSize: "42mm",
    strapSize: "22mm",
    warranty: "1 Year Machine Warranty",
    stock: 4,
    rating: 4.9,
    reviews: 31,
    shortDescription: "Open-heart automatic on black alligator-grain leather.",
    description: "Night Tourbillon Style shows the beating heart of the movement through an open dial — a conversation piece for collectors.",
    features: ["Open Heart", "Automatic", "Alligator Grain", "Sapphire Coat"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-034",
    name: "Weekend Canvas",
    slug: "weekend-canvas",
    sku: "TMR-WC-034",
    category: ["casual"],
    price: 2490,
    originalPrice: 3290,
    discount: 24,
    images: g("vintage", "leather", "classic", "wrist", "urban"),
    colors: [
      { name: "Tan", hex: "#D97706", imageIndex: 0 },
      { name: "Olive", hex: "#4D7C0F", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Leather",
    caseMaterial: "Alloy",
    dialColor: "Sand",
    waterResistance: "3 ATM",
    caseSize: "38mm",
    strapSize: "18mm",
    warranty: "1 Year Machine Warranty",
    stock: 24,
    rating: 4.4,
    reviews: 44,
    shortDescription: "Lightweight weekend watch with warm sand dial.",
    description: "Weekend Canvas is easy, warm and inexpensive — the watch you actually wear on Fridays.",
    features: ["Sand Dial", "Light 42g", "Quick-release Strap"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-035",
    name: "Sweetheart Duo Mini",
    slug: "sweetheart-duo-mini",
    sku: "TMR-SDM-035",
    category: ["couple", "womens"],
    price: 6290,
    originalPrice: 7990,
    discount: 21,
    images: g("couple2", "rose", "petite", "wrist", "crystal"),
    colors: [
      { name: "Rose Gold", hex: "#B76E79", imageIndex: 0 },
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
    ],
    movement: "Quartz",
    strap: "Mesh",
    caseMaterial: "Stainless Steel",
    dialColor: "Blush / Silver",
    waterResistance: "3 ATM",
    caseSize: "38mm / 28mm",
    strapSize: "18mm / 12mm",
    warranty: "1 Year Machine Warranty",
    stock: 8,
    rating: 4.8,
    reviews: 55,
    shortDescription: "Petite couple set with blush mesh — a sweet gift.",
    description: "Sweetheart Duo Mini is a romantic pair with matching mesh straps and a compact her-size case.",
    features: ["Petite Pair", "Mesh", "Gift Ready"],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "tmr-036",
    name: "Titanium Everyday",
    slug: "titanium-everyday",
    sku: "TMR-TE-036",
    category: ["mens", "casual", "premium"],
    price: 7990,
    originalPrice: 9990,
    discount: 20,
    images: g("mesh", "classic", "blue", "wrist", "chrono"),
    colors: [
      { name: "Silver", hex: "#C0C0C0", imageIndex: 0 },
      { name: "Grey", hex: "#6B7280", imageIndex: 1 },
    ],
    movement: "Quartz",
    strap: "Mesh",
    caseMaterial: "Titanium-look Steel",
    dialColor: "Silver",
    waterResistance: "5 ATM",
    caseSize: "40mm",
    strapSize: "20mm",
    warranty: "1 Year Machine Warranty",
    stock: 10,
    rating: 4.7,
    reviews: 37,
    shortDescription: "Feather-light mesh watch for all-day wear.",
    description: "Titanium Everyday is the lightest TIMEORA dress-casual hybrid — mesh bracelet, 40mm case, five-atmosphere rating.",
    features: ["Ultra Light", "Mesh Bracelet", "40mm", "5 ATM"],
    isFeatured: true,
    isNew: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(cat: ProductCategory): Product[] {
  return products.filter(p => p.category.includes(cat));
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.isFeatured);
}

export function getBestSellers(): Product[] {
  return products.filter(p => p.isBestSeller);
}

export function getNewProducts(): Product[] {
  return products.filter(p => p.isNew);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(p => p.id !== product.id && p.category.some(c => product.category.includes(c)))
    .slice(0, limit);
}

export const categories = [
  { id: "mens", label: "Men's Watches", slug: "mens", image: I.chrono, accent: "#0E1630", count: products.filter(p => p.category.includes("mens")).length },
  { id: "womens", label: "Women's Watches", slug: "womens", image: I.rose, accent: "#C4787A", count: products.filter(p => p.category.includes("womens")).length },
  { id: "couple", label: "Couple Watches", slug: "couple", image: I.couple, accent: "#C9A24A", count: products.filter(p => p.category.includes("couple")).length },
  { id: "smart", label: "Smart Watches", slug: "smart", image: I.smart, accent: "#1F7A5C", count: products.filter(p => p.category.includes("smart")).length },
  { id: "casual", label: "Casual Watches", slug: "casual", image: I.leather, accent: "#92400E", count: products.filter(p => p.category.includes("casual")).length },
  { id: "premium", label: "Premium Collection", slug: "premium", image: I.midnight, accent: "#080D1C", count: products.filter(p => p.category.includes("premium")).length },
] as const;

export const heroImage = I.hero;
